CC = gcc
CFLAGS = -nostdlib -masm=intel -Ilib -fno-stack-protector -Os -g
LDFLAGS = -nostdlib -static -z nodefaultlib -e _start -Tminimal.ld -Wl,--build-id=none
OBJDIR = obj
SRCDIR = src
DISTDIR = dist

MAIN_SRC = FlipVM.c
MAIN_OBJ = $(OBJDIR)/FlipVM.o

SRC_FILES := $(wildcard $(SRCDIR)/*.c)
OBJ_FILES := $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(SRC_FILES)) $(MAIN_OBJ)

TARGET = $(DISTDIR)/FlipVM


all: $(TARGET)

$(TARGET): $(OBJ_FILES) $(MAIN_OBJ)
	@mkdir -p $(DISTDIR)
	$(CC) $(CFLAGS) $(OBJ_FILES) $(LDFLAGS) -o $@
	strip --strip-all $(TARGET)


$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@


$(MAIN_OBJ): $(MAIN_SRC)
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	rm -rdf $(OBJDIR) $(DISTDIR)

force:
	$(MAKE) clean
	$(MAKE) all

.PHONY: all clean force debug
debug:
	$(MAKE) clean
	$(MAKE) CFLAGS="$(CFLAGS) -DDEBUG" all
