#!/usr/bin/env python3
"""
Prometheora keygen (static reconstruction, no target execution required).

Recovered from Binary Ninja analysis:
- key bytes are generated by sub_430410 LCG stream XOR data_40d993
- resulting candidate is validated against reconstructed sub_439610 stages

Usage:
    python3 prometheora_keygen.py
"""

from __future__ import annotations

MASK64 = (1 << 64) - 1

# sub_430410 constants
LCG_SEED = 0x7A3F8C91D2E5B4A6
LCG_MUL = 0x5851F42D4C957F2D
LCG_INC = 0x14057B7EF767814F

# data_40d993 (28 bytes)
XOR_TABLE = bytes.fromhex(
    "12 32 10 ef d7 56 ed 3f 58 99 e7 59 df 63 03 bf"
    " 04 8e 25 5b f2 4a b9 13 9c 22 da 6c"
)


def u64(x: int) -> int:
    return x & MASK64


def rol(x: int, b: int) -> int:
    b &= 63
    return u64((x << b) | (x >> (64 - b)))


def sip_round(v0: int, v1: int, v2: int, v3: int) -> tuple[int, int, int, int]:
    v0 = u64(v0 + v1)
    v1 = rol(v1, 13)
    v1 ^= v0
    v0 = rol(v0, 32)

    v2 = u64(v2 + v3)
    v3 = rol(v3, 16)
    v3 ^= v2

    v0 = u64(v0 + v3)
    v3 = rol(v3, 21)
    v3 ^= v0

    v2 = u64(v2 + v1)
    v1 = rol(v1, 17)
    v1 ^= v2
    v2 = rol(v2, 32)
    return v0, v1, v2, v3


def sub_43a320(data: bytes, k0: int, k1: int) -> int:
    """Reconstruction of sub_43a320 (SipHash-like keyed compression)."""
    v0 = 0x736F6D6570736575 ^ u64(k0)
    v1 = 0x646F72616E646F6D ^ u64(k1)
    v2 = 0x6C7967656E657261 ^ u64(k0)
    v3 = 0x7465646279746573 ^ u64(k1)

    i = 0
    n = len(data)
    while i + 8 <= n:
        m = int.from_bytes(data[i:i + 8], "little")
        v3 ^= m
        v0, v1, v2, v3 = sip_round(v0, v1, v2, v3)
        v0, v1, v2, v3 = sip_round(v0, v1, v2, v3)
        v0 ^= m
        i += 8

    b = (n & 0xFF) << 56
    for j, c in enumerate(data[i:]):
        b |= c << (8 * j)

    v3 ^= b
    v0, v1, v2, v3 = sip_round(v0, v1, v2, v3)
    v0, v1, v2, v3 = sip_round(v0, v1, v2, v3)
    v0 ^= b
    v2 ^= 0xFF

    for _ in range(4):
        v0, v1, v2, v3 = sip_round(v0, v1, v2, v3)

    return u64(v0 ^ v1 ^ v2 ^ v3)


def mix64(x: int) -> int:
    """Murmur-style finalizer used in sub_439be0."""
    x = u64(x)
    x ^= x >> 33
    x = u64(x * 0xFF51AFD7ED558CCD)
    x ^= x >> 33
    x = u64(x * 0xC4CEB9FE1A85EC53)
    x ^= x >> 33
    return u64(x)


def sconst(x: int) -> int:
    return u64(x)


SEG_TARGETS = [
    0x64AB81FECCE00947,
    0x6836A10A23DD8E77,
    0xB4A1E70DFF5EC991,
    0x53966B588E01C554,
]

POLY_TARGETS = [
    0xD6F3AD7FCF60E599,
    0x61AF7543C53E1E80,
    0x2B54EF961ABDF2AF,
    0x6D7B46529261B90E,
    0xF0983FE510642916,
]


def generate_key_bytes() -> bytes:
    state = LCG_SEED
    out = bytearray()
    for i in range(0x1C):
        state = u64(state * LCG_MUL + LCG_INC)
        out.append(((state >> 32) & 0xFF) ^ XOR_TABLE[i])
    return bytes(out)


def verify_sub_439610(key: bytes) -> bool:
    if len(key) != 0x1C:
        return False

    # sub_4396a0
    if not all((0x41 <= c <= 0x5A) or (0x30 <= c <= 0x39) or c == 0x5F for c in key):
        return False
    if key.count(0x5F) != 3:
        return False
    if sum(key) != 0x778:
        return False

    # sub_439840 + sub_439888
    if not (key[10] == key[15] == key[23] == 0x5F):
        return False
    if not all(0x30 <= c <= 0x39 for c in key[24:28]):
        return False
    if sub_43a320(key[24:28], 0x5945415248415348, 0x4B45593031303230) != sconst(-0x3BCFECA119AAAD63):
        return False

    # sub_4398e0
    if sub_43a320(key, sconst(-0x2152411035014542), 0x0123456789ABCDEF) != sconst(-0x06CFC51A936B765B):
        return False

    # sub_439950
    if sub_43a320(key, sconst(-0x0123456789ABCDF0), 0x1111111111111111) != sconst(-0x3C8EDAE5D64F271E):
        return False

    # sub_4399c0
    if sub_43a320(key, sconst(-0x5555555555555556), 0x5555555555555555) != sconst(-0x5B652C3D3EC4CEA2):
        return False

    # sub_439a30 (4x7-byte chunks)
    ks = [
        (0x1234567890ABCDEF, sconst(-0x012345F6789ABCDF)),
        (0x23456789A1BCDF00, sconst(-0x0234568189ABCDF01)),
        (0x3456789AB2CDF011, sconst(-0x45678A3ABCDF0123)),
        (0x456789ABC3DF0122, sconst(-0x6789AC5CDF012345)),
    ]
    for i in range(4):
        h = sub_43a320(key[i * 7:(i + 1) * 7], ks[i][0], ks[i][1])
        if h != SEG_TARGETS[i]:
            return False

    # sub_439be0 (polynomial fingerprints)
    xs = [0x17, 0x2B, 0x3D, 0x4F, 0x61]
    for idx, x in enumerate(xs):
        p = 1
        v = 0
        for c in key:
            v = u64(v + p * c)
            p = u64(p * x)
        if mix64(v) != POLY_TARGETS[idx]:
            return False

    return True


def main() -> int:
    key = generate_key_bytes()
    text = key.decode("ascii")
    print(text)

    if verify_sub_439610(key):
        print("[+] static validation model: PASS")
        return 0
    print("[-] static validation model: FAIL")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
