(() => {
  'use strict';
  const $=id=>document.getElementById(id); let config={max_file_bytes:0,max_total_bytes:0};
  const size=n=>{if(!Number.isFinite(n))return '0 B';const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return `${n.toFixed(i?1:0)} ${units[i]}`;};
  const date=value=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
  function message(text,error=false){$('upload-status').textContent=text;$('upload-status').classList.toggle('error',error);}
  async function load(){try{const response=await fetch('../api/fileshare',{cache:'no-store'});if(!response.ok)throw Error('Unable to load shared files.');const data=await response.json();config=data;$('limit').textContent=`Maximum ${size(data.max_file_bytes)} per file`;render(data);}catch(error){message(error.message,true);}}
  function render(data){$('count').textContent=`${data.files.length} file${data.files.length===1?'':'s'}`;$('usage-text').textContent=`${size(data.usage_bytes)} used of ${size(data.max_total_bytes)}`;$('usage-bar').style.width=`${Math.min(100,data.usage_bytes/data.max_total_bytes*100)||0}%`;$('empty').hidden=data.files.length!==0;const root=$('files');root.replaceChildren(...data.files.map(file=>{const row=document.createElement('article');row.className='file';const info=document.createElement('div'),name=document.createElement('div'),meta=document.createElement('div'),hash=document.createElement('div'),link=document.createElement('a');name.className='name';name.textContent=file.name;meta.className=hash.className='meta';meta.textContent=`${size(file.size)} · ${date(file.uploaded_at)}`;hash.textContent=`SHA-256 ${file.sha256.slice(0,16)}…`;info.append(name,meta);link.className='button';link.href=`../api/fileshare/download/${encodeURIComponent(file.id)}`;link.textContent='Download';link.setAttribute('download',file.name);row.append(info,hash,link);return row;}));}
  async function upload(files){for(const file of files){if(config.max_file_bytes&&file.size>config.max_file_bytes){message(`${file.name} exceeds the ${size(config.max_file_bytes)} limit.`,true);continue;}message(`Uploading ${file.name}…`);$('progress').hidden=false;$('progress').value=0;try{await send(file);message(`${file.name} uploaded.`);}catch(error){message(`${file.name}: ${error.message}`,true);break;}}$('progress').hidden=true;await load();}
  function send(file){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`../api/fileshare?filename=${encodeURIComponent(file.name)}`);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)$('progress').value=e.loaded/e.total*100;};xhr.onload=()=>{let data={};try{data=JSON.parse(xhr.responseText);}catch{}xhr.status===201?resolve(data):reject(Error(data.error||`Upload failed (${xhr.status})`));};xhr.onerror=()=>reject(Error('Network error during upload.'));xhr.send(file);});}
  const drop=$('drop');['dragenter','dragover'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add('drag');}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('drag');}));drop.addEventListener('drop',event=>upload([...event.dataTransfer.files]));$('picker').addEventListener('change',event=>{upload([...event.target.files]);event.target.value='';});$('refresh').addEventListener('click',load);load();
})();
