(() => {'use strict';const $=id=>document.getElementById(id),state={data:null,query:'',fn:'',context:'',visible:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function contextNames(bin){const names=new Set;Object.values(bin.functions).flat().forEach(item=>Object.keys(item.contexts||{}).forEach(x=>names.add(x)));return names}
function match(bin){const terms=state.query.toLowerCase().trim().split(/\s+/).filter(Boolean),functions=Object.keys(bin.functions),contexts=contextNames(bin);if(state.fn&&!functions.includes(state.fn))return false;if(state.context&&!contexts.has(state.context))return false;const hay=`${bin.name} ${bin.aliases.join(' ')} ${functions.join(' ')} ${JSON.stringify(bin.functions)}`.toLowerCase();return terms.every(t=>hay.includes(t))}
function list(){state.visible=state.data.bins.filter(match);$('count').textContent=`${state.visible.length} / ${state.data.count} executables`;$('bins').innerHTML=state.visible.map(x=>`<button class="bin" data-name="${esc(x.name)}">${esc(x.name)}</button>`).join('');document.querySelectorAll('.bin').forEach(x=>x.addEventListener('click',()=>select(x.dataset.name)));const wanted=decodeURIComponent(location.hash.slice(1));if(state.visible.some(x=>x.name===wanted))select(wanted,false);else if(state.visible[0])select(state.visible[0].name,true);else $('detail').innerHTML='<p class="empty">No executable matches the current search and filters.</p>'}
function codeBlock(code){return `<pre><button class="copy" type="button">Copy</button><code>${esc(code)}</code></pre>`}
function select(name,update=true){const bin=state.data.bins.find(x=>x.name===name);if(!bin)return;if(update)history.replaceState(null,'',`#${encodeURIComponent(name)}`);document.querySelectorAll('.bin').forEach(x=>x.classList.toggle('active',x.dataset.name===name));$('side').classList.remove('open');let html=`<div class="eyebrow">Unix executable reference</div><h1>${esc(bin.name)}</h1>${bin.aliases.length?`<p class="lede">Aliases: ${bin.aliases.map(esc).join(', ')}</p>`:''}${bin.comment?`<div class="notice">${esc(bin.comment)}</div>`:''}<div class="notice">These techniques depend on local misconfiguration or delegated privileges. Test only within authorized systems and CTF labs.</div>`;for(const[fn,cases]of Object.entries(bin.functions)){const def=state.data.function_definitions[fn]||{};html+=`<section class="function"><h2>${esc(def.label||fn)}</h2><p class="muted">${esc(def.description||'')}</p>${cases.map(item=>{const contexts=Object.keys(item.contexts||{});let body=`<article class="case"><div class="case-head"><div class="contexts">${contexts.map(x=>`<span class="context">${esc(state.data.context_definitions[x]?.label||x)}</span>`).join('')}</div></div>${item.comment?`<p>${esc(item.comment)}</p>`:''}${item.code?codeBlock(item.code):''}`;for(const[name,value]of Object.entries(item.contexts||{}))if(value&&typeof value==='object'&&value.code)body+=`<div class="override"><b>${esc(state.data.context_definitions[name]?.label||name)} variant</b>${codeBlock(value.code)}</div>`;return body+'</article>'}).join('')}</section>`}$('detail').innerHTML=html;document.querySelectorAll('.copy').forEach(button=>button.addEventListener('click',async()=>{await navigator.clipboard.writeText(button.nextElementSibling.textContent);button.textContent='Copied';setTimeout(()=>button.textContent='Copy',1000)}));}
function filters(id,values,key,definitions){$(id).innerHTML=`<button class="chip active" data-value="">All</button>${values.map(x=>`<button class="chip" data-value="${esc(x)}">${esc(definitions[x]?.label||x)}</button>`).join('')}`;$(id).addEventListener('click',e=>{const b=e.target.closest('[data-value]');if(!b)return;state[key]=b.dataset.value;[...$(id).children].forEach(x=>x.classList.toggle('active',x===b));list()})}
function query(value){state.query=value;$('search').value=$('mobile-search').value=value;list()}let timer;['search','mobile-search'].forEach(id=>$(id).addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>query(e.target.value),100)}));$('menu').addEventListener('click',()=>$('side').classList.toggle('open'));addEventListener('hashchange',()=>select(decodeURIComponent(location.hash.slice(1)),false));
fetch('data.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(data=>{state.data=data;const f=[...new Set(data.bins.flatMap(x=>Object.keys(x.functions)))].sort(),c=[...new Set(data.bins.flatMap(x=>[...contextNames(x)]))].sort();filters('function-filters',f,'fn',data.function_definitions);filters('context-filters',c,'context',data.context_definitions);$('revision').textContent=`Snapshot ${data.commit.slice(0,12)}.`;list();const wanted=decodeURIComponent(location.hash.slice(1));select(data.bins.some(x=>x.name===wanted)?wanted:data.bins[0].name,false)}).catch(error=>$('detail').innerHTML=`<p class="empty">Could not load the local snapshot: ${esc(error.message)}</p>`);
})();
